server.port: 8180
spring.jpa.generate-ddl: true
spring.jpa.show-sql: false
spring.jpa.hibernate.ddl-auto: update
spring.main.allow-circular-references: true
server.error.include-message: always
jwt.expiration: 86400000
